# server:
#   port: 8087
#   servlet:
#     context-path: '/ead-authuser/'

spring:
  application:
    name: ead-authuser-service
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
      username: configserver
      password: 'ead123cs'

#   datasource:
#     url: jdbc:postgresql://localhost:5432/ead_authuser_v2
#     username: admin
#     password: admin
#   jpa:
#     hibernate:
#       ddl-auto: update
#       dialect: org.hibernate.dialect.PostgreSQLDialect
#       jdbc:
#         lob.non-contextual-creation: true
#     properties:
#       hibernate:
#         show_sql: true
#   output:
#     ansi:
#       enabled: Always
#   rabbitmq:
#     addresses: amqps://jdxywwwj:AK4ygMqsVn5gfEUjYuQYO4GQfkSbZgz_@gerbil.rmq.cloudamqp.com/jdxywwwj

# logging:
#   level:
#     com.ead.: TRACE
#     root: INFO
#     org.springframework.web: DEBUG
#     org.hibernate: INFO

# ead:
#   api:
#     url:
#       course: 'http://ead-course-service/ead-course'
#   broker:
#     exchange:
#       userEvent: ead.userevent

# eureka:
#   client:
#     service-url:
#       default-zone: 'http://localhost:8761/eureka'
#   instance:
#     hostname: localhost

# resilience4j:
#   circuitbreaker:
#     instances:
#       circuitbrakerInstace:
#         slidingWindowSize: 30
#         permittedNumberOfCallsInHalfOpenState: 2
#         slidingWindowType: TIME_BASED
#         minimumNumberOfCalls: 2
#         waitDurationInOpenState: 30s
#         failureRateThreshold: 80
#   retry:
#     instances:
#       retryInstance:
#         maxAttempts: 3
#         waitDuration: 5s
