server:
  port: 8888

spring: 
  application: 
    name: ead-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/devadilson/ead-config-server-repo
          default-label: main

eureka:
  client:
    service-url:
      daultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost