server:
  port: 8888 #${PORT}

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/devadilson/ead-config-server-repo #${}}
          default-label: main #${GIT_BRANCH}
          #username: ${GIT_USERNAME}
          #password: ${GIT_PASSWORD}

#encrypt:
#  key: S8IAxIaP00YSSRCrG9PYGMTw6KsUUTKk

ead:
  configServer:
    username: configserver #${CONFIG_SERVER_USERNAME}
    password: 'ead123cs' #${CONFIG_SERVER_PASSWORD}
  serviceRegistry: #ESSA PROPRIEDADE PODE SER REMOVIDA, POIS A URL EUREKA_CLIENT IRA VIR COM OS DADOS
    username: serviceregistry #${} #ESSA PROPRIEDADE PODE SER REMOVIDA, POIS A URL EUREKA_CLIENT IRA VIR COM OS DADOS
    password: 'ead123sr' #ESSA PROPRIEDADE PODE SER REMOVIDA, POIS A URL EUREKA_CLIENT IRA VIR COM OS DADOS

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka' #${EUREKA_URL}
  instance:
    hostname: localhost #${APP_DOMAIN_NAME}
    #non-secure-port: 80

encrypt:
  key: SUN9Ea8uMa0vJyZmDU/lWILyL8Jj5KXmh5y0qLEy0YnjqNtUnrLvKiOeFyXpS3+C